{{- if eq .Values.kind "CronJob" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "buffdata.fullname" . }}
  labels:
    {{- include "buffdata.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.backoffLimit }}
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
      template:
        {{- include "buffdata.podTemplate" . | nindent 8 }}
{{- end }}
