{{- if eq .Values.kind "Job" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "buffdata.fullname" . }}
  labels:
    {{- include "buffdata.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
  template:
    {{- include "buffdata.podTemplate" . | nindent 4 }}
{{- end }}
